[versions]
kotlinxDatetime = "0.7.1"
agp = "8.13.0"
android-compileSdk = "35"
android-minSdk = "24"
android-targetSdk = "35"
androidx-activity = "1.12.0-rc01"
androidx-appcompat = "1.7.1"
androidx-core = "1.17.0"
androidx-espresso = "3.7.0"
androidx-lifecycle = "2.9.5"
androidx-testExt = "1.3.0"
androidx-constraintlayout = "2.2.1"
composeHotReload = "1.0.0-rc03"
composeMultiplatform = "1.9.3"
junit = "4.13.2"
kotlin = "2.2.21"
kotlinx-coroutines = "1.10.2"
kodeinDi = "7.29.0"
ktorfit = "2.6.4"
kottage = "1.9.0"
ktor = "3.3.2"
navigationCompose = "2.8.0-alpha10"
pagingRuntime = "3.3.6"
pagingComposeCommon = "3.4.0-alpha04"
material = "1.7.3"
material3 = "1.10.0-alpha04"
uiAndroid = "1.8.0"
coil3 = "3.3.0"
voyager = "1.1.0-beta03"
ksp = "2.3.2"
room = "2.7.1"
sqlite = "2.5.1"
sqlDelight = "2.1.0"
sketch = "4.3.1"
zoomimage = "1.4.0"
cashPaging = "3.3.0-alpha02-0.5.1"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-testExt-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-testExt" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kodein-di = { module = "org.kodein.di:kodein-di", version.ref = "kodeinDi" }
kodein-di-compose = { module = "org.kodein.di:kodein-di-framework-compose", version.ref = "kodeinDi" }
kottage = { module = "io.github.irgaly.kottage:kottage", version.ref = "kottage" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-serialization-gson = { module = "io.ktor:ktor-serialization-gson", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktorfit-lib = { module = "de.jensklingenberg.ktorfit:ktorfit-lib", version.ref = "ktorfit" }
ktorfit-ksp = { module = "de.jensklingenberg.ktorfit:ktorfit-ksp", version.ref = "ktorfit" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "pagingRuntime" }
paging-common = { module = "androidx.paging:paging-common", version.ref = "pagingRuntime" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingComposeCommon" }
material-icons = { group = "org.jetbrains.compose.material", name = "material-icons-core", version.ref = "material" }
material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "material3" }
material3-desktop = { group = "org.jetbrains.compose.material3", name = "material3-desktop", version.ref = "material3" }
material3-window-size = { group = "org.jetbrains.compose.material3", name = "material3-window-size-class", version.ref = "material3" }
material3-adaptive-navigation = { group = "org.jetbrains.compose.material3", name = "material3-adaptive-navigation-suite", version.ref = "material3" }
androidx-ui-android = { group = "androidx.compose.ui", name = "ui-android", version.ref = "uiAndroid" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil3" }
#coil-network = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil3" }
coil-network = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil3" }
# voyager
voyager-navigator = { group = "cafe.adriel.voyager", name = "voyager-navigator", version.ref = "voyager" }
voyager-screenmodel = { group = "cafe.adriel.voyager", name = "voyager-screenmodel", version.ref = "voyager" }
voyager-bottom-sheet-navigator = { group = "cafe.adriel.voyager", name = "voyager-bottom-sheet-navigator", version.ref = "voyager" }
voyager-tab-navigator = { group = "cafe.adriel.voyager", name = "voyager-tab-navigator", version.ref = "voyager" }
voyager-transitions = { group = "cafe.adriel.voyager", name = "voyager-transitions", version.ref = "voyager" }
voyager-kodein = { group = "cafe.adriel.voyager", name = "voyager-kodein", version.ref = "voyager" }
# Room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
# sqlDelight
sqldelight-android-driver = { group = "app.cash.sqldelight", name = "android-driver", version.ref = "sqlDelight" }
sqldelight-native-driver = { group = "app.cash.sqldelight", name = "native-driver", version.ref = "sqlDelight" }
sqldelight-sqlite-driver = { group = "app.cash.sqldelight", name = "sqlite-driver", version.ref = "sqlDelight" }
sqldelight-coroutines = { group = "app.cash.sqldelight", name = "coroutines-extensions", version.ref = "sqlDelight" }
sqldelight-paging3 = { group = "app.cash.sqldelight", name = "androidx-paging3-extensions", version.ref = "sqlDelight" }
sqldelight-runtime = { group = "app.cash.sqldelight", name = "runtime", version.ref = "sqlDelight" }
sqldelight-sqlite-dialect = { group = "app.cash.sqldelight", name = "sqlite-3-24-dialect", version.ref = "sqlDelight" }
# sketch
sketch-compose = { group = "io.github.panpf.sketch4", name = 'sketch-compose', version.ref = "sketch" }
sketch-http = { group = "io.github.panpf.sketch4", name = 'sketch-http', version.ref = "sketch" }
#使用 Android 或 Skia 内置的解码器解码 gif 动图并播放
sketch-animated-gif = { group = "io.github.panpf.sketch4", name = 'sketch-animated-gif', version.ref = "sketch" }
#使用 Android 或 Skia 内置的解码器解码 webp 动图并播放
sketch-animated-webp = { group = "io.github.panpf.sketch4", name = 'sketch-animated-webp', version.ref = "sketch" }
# 支持通过 uri 或 placeholder、fallback、error 访问 compose resources 资源
sketch-compose-resources = { group = "io.github.panpf.sketch4", name = 'sketch-compose-resources', version.ref = "sketch" }
sketch-extensions-compose-resources = { group = "io.github.panpf.sketch4", name = 'sketch-extensions-compose-resources', version.ref = "sketch" }
#提供下载进度、图片类型角标、列表滚动中暂停加载、节省蜂窝流量等实用功能
sketch-extensions-compose = { group = "io.github.panpf.sketch4", name = 'sketch-extensions-compose', version.ref = "sketch" }
sketch-ktor = { group = "io.github.panpf.sketch4", name = 'sketch-http-ktor3', version.ref = "sketch" }
sketch-svg = { group = "io.github.panpf.sketch4", name = 'sketch-svg', version.ref = "sketch" }
#cash paging
#cash-paging = { group = "androidx.paging", name = "paging-common", version.ref = "cashPaging" }
#cash-paging-common = { group = "androidx.paging", name = "paging-compose-common", version.ref = "cashPaging" }

# zoom
zoom = { group = "io.github.panpf.zoomimage", name = "zoomimage-compose", version.ref = "zoomimage" }
zoom-sketch = { group = "io.github.panpf.zoomimage", name = "zoomimage-compose-sketch4", version.ref = "zoomimage" }
zoom-resources = { group = "io.github.panpf.zoomimage", name = "zoomimage-compose-resources", version.ref = "zoomimage" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqlDelight" }
room = { id = "androidx.room", version.ref = "room" }
